server:
  port: 8083

spring:
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/nancal_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    clean-disabled: true
    table: db_schema
    baseline-on-migrate: true
    ignore-future-migrations: true
    locations: classpath:/db/
minio:
  #  endpoint: http://saas-dev.nancal.com:31020 #Minio服务所在地址
  endpoint: http://localhost:9000 #Minio服务所在地址
  #  bucketName: minio-bucket1 #存储桶名称
  bucketName: bucket #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
#  accessKey: admin #访问的key
#  secretKey: admin.123 #访问的秘钥
