server:
  port: 8080
  servlet:
    context-path: /nancal-demo

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/nancal_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    clean-disabled: true
    table: db_schema
    baseline-on-migrate: true
    ignore-future-migrations: true
    locations: classpath:/db/

